//! Embeds the token-decode table generated by `llm-host`'s `vocab-to-bin`
//! tool (`assets/vocab_blob.bin` + `assets/vocab_off.bin`, built from
//! `reference-c/esp32-llm-lab/vocab.h` -- see that tool for how the two
//! files are produced, and its round-trip check confirming this is the
//! same vocab table `esp32_llm.ino`'s hardcoded `PROMPT_IDS` decode
//! against: `{433, 447, 259, 405}` -> "Once upon a time").
//!
//! Ports the token-id-to-bytes lookup in `esp32_llm.ino`'s `emit()`
//! (`VOCAB_BLOB + VOCAB_OFF[tok]`, length `VOCAB_OFF[tok+1] - VOCAB_OFF[tok]`)
//! and the `VOCAB_N` constant -- derived here from the offset table's own
//! length instead of a separately-generated `#define`, so the two can't
//! silently drift out of sync with each other.

static VOCAB_BLOB: &[u8] = include_bytes!("../assets/vocab_blob.bin");
static VOCAB_OFF_BYTES: &[u8] = include_bytes!("../assets/vocab_off.bin");

/// Number of trained vocab entries (`VOCAB_N` in the C reference) --
/// distinct from `model.cfg.vocab`, which includes padding rows above
/// this that have no decode entry here and are never scored by the
/// staged head (see `head::stage_and_spawn`'s doc comment) or the greedy
/// argmax in `main`.
pub fn vocab_n() -> usize {
    VOCAB_OFF_BYTES.len() / 4 - 1
}

fn off(i: usize) -> usize {
    let b = i * 4;
    u32::from_le_bytes([
        VOCAB_OFF_BYTES[b],
        VOCAB_OFF_BYTES[b + 1],
        VOCAB_OFF_BYTES[b + 2],
        VOCAB_OFF_BYTES[b + 3],
    ]) as usize
}

/// Token id -> its decode bytes, or `None` for an out-of-range id (mirrors
/// C's `if (tok >= VOCAB_N) return;` guard at the top of `emit()`).
pub fn decode(tok: usize) -> Option<&'static [u8]> {
    if tok >= vocab_n() {
        return None;
    }
    let start = off(tok);
    let end = off(tok + 1);
    Some(&VOCAB_BLOB[start..end])
}
